In [1]:
import pandas as pd
import numpy as np

paths = pd.read_fwf('train_paths.csv', header=None,infer_nrows=4251)
paths = paths[0].str.split(',', expand=True)
paths.replace(to_replace=[None], value= -1, inplace=True)

profit = pd.read_csv('profit(0:8554).csv',header = None)

In [2]:
paths

,0,1,2,3,4,5,6,7,8,9,...,224,225,226,227,228,229,230,231,232,233
0,28777,28045.0,28046.0,28047.0,30135.0,28873.0,28872.0,27818.0,27819.0,27820.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
1,52455,52454.0,52453.0,52491.0,47681.0,47682.0,47683.0,47684.0,47685.0,47686.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
2,36506,36507.0,39755.0,39204.0,39207.0,-1,-1,-1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
3,25977,26004.0,26005.0,25992.0,25993.0,26415.0,26416.0,26417.0,27815.0,27816.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
4,37341,37342.0,37343.0,37344.0,36584.0,39203.0,-1,-1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8550,55037,55036.0,55400.0,54718.0,54719.0,55344.0,55345.0,55346.0,55347.0,55348.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
8551,55037,55036.0,55400.0,54718.0,54719.0,55344.0,55345.0,55346.0,55347.0,55348.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
8552,57465,57464.0,57482.0,57481.0,57922.0,57921.0,58021.0,58042.0,57915.0,57212.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
8553,49595,45993.0,45992.0,45991.0,46021.0,50867.0,49426.0,51535.0,46504.0,46118.0,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1
8554,55401,55036.0,55037.0,54989.0,54990.0,54991.0,-1,-1,-1,-1,...,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1

In [3]:
paths = paths.apply(pd.to_numeric)
a = (paths.values)
a.sort(axis=1)
a = a[:, ::-1]
len_path = []
for j,path in enumerate(a):
    l = np.count_nonzero(path+1)
    len_path.append(l)

In [4]:
ratio_path = []
for i,pro in profit.iterrows():
    ratio_path.append(pro[0]/len_path[i])

In [5]:
pd.DataFrame(ratio_path).to_csv('ratio(0:8554).csv',index=False,header=False)

In [6]:
pd.DataFrame(len_path).to_csv('length(0:8554).csv',index=False,header=False)

In [7]:
#merge

In [8]:
ratio = pd.read_csv('ratio(0:8554).csv',header = None)
profit = pd.read_csv('profit(0:8554).csv',header = None)
length = pd.read_csv('length(0:8554).csv',header = None)

In [9]:
paths = pd.read_fwf('train_paths.csv', header=None,infer_nrows=4251)
paths = paths[0].str.split(',', expand=True)
paths.replace(to_replace=[None], value= -1, inplace=True)
#paths.head()
paths = paths.apply(pd.to_numeric)
a = (paths.values)
a.sort(axis=1)
a = a[:, ::-1]

In [10]:
frames = [ratio, profit, length]
merge = pd.concat(frames,ignore_index=True,axis = 1)

In [11]:
merge.to_csv('ratio-profit-length(0:9613).csv',index=False,header=False)

In [12]:
sorted_merge = merge.sort_values(by=[0], ascending=False)

In [13]:
sorted_merge.to_csv('sorted-ratio-profit-length(0:9613).csv',header=False)